# O Nome do seu Site
site_name: LAB Desec

# A URL final (para corrigir as imagens)
site_url: https://legitwell.github.io/Vlabs/

# [CORREÇÃO]
# Agora nós dizemos a ele que nossas notas estão na pasta 'docs'
# (Este é o padrão, mas é bom ser explícito)
docs_dir: docs

# O Tema que instalamos
theme:
  name: material
  
  # Paleta de Cores (Modo Escuro "Hacker")
  palette:
    scheme: slate
    primary: red
    accent: red

# Plugins (Para a barra de busca)
plugins:
  - search